/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmlpars.gui;

import javax.swing.JList;
import kmlpars.KMLPars;

/**
 *
 * @author dmitry
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
//    DefaultListModel defaultListModel = new DefaultListModel();
    public Main() {
        initComponents();           

    }

    public JList<String> getjList1() {
        return jList1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnNewWord = new javax.swing.JButton();
        btnAddLang = new javax.swing.JButton();
        btnAddUsage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KML Parsing");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        btnNewWord.setText("Add word");
        btnNewWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewWordMouseClicked(evt);
            }
        });

        btnAddLang.setText("Add Lang");
        btnAddLang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddLangMouseClicked(evt);
            }
        });

        btnAddUsage.setText("Add Usage");
        btnAddUsage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUsageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddUsage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddLang)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewWord)
                    .addComponent(btnAddLang)
                    .addComponent(btnAddUsage))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        WordGui word = new WordGui(jList1.getSelectedValue());
        word.setVisible(true);
    }//GEN-LAST:event_jList1MouseClicked

    private void btnAddLangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLangMouseClicked
        KMLPars.NEW_LANG.setVisible(true);
    }//GEN-LAST:event_btnAddLangMouseClicked

    private void btnAddUsageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUsageMouseClicked
        KMLPars.NEW_USAGE.setVisible(true);
    }//GEN-LAST:event_btnAddUsageMouseClicked

    private void btnNewWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewWordMouseClicked
        new NewWord().setVisible(true);
    }//GEN-LAST:event_btnNewWordMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLang;
    private javax.swing.JButton btnAddUsage;
    private javax.swing.JButton btnNewWord;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
