/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kmlpars.gui;

import kmlpars.beans.Word;
import kmlpars.service.Constants;
import kmlpars.service.WordWorker;

/**
 *
 * @author dmitry
 */
public class WordGui extends javax.swing.JFrame {

    /**
     * Creates new form Word
     */
    public WordGui() {
        initComponents();
    }

    WordGui(String selectedValue) {
        initComponents();
        this.setTitle(selectedValue);
        Word word = WordWorker.getWordByName(selectedValue);
        
        this.t_desc_.setText(word.getDescription());
        this.t_usage_.setText(word.getUsage().getTitle().getName());
        this.t_lang.setText(word.getLang().getTitle().getName());
        this.t_origName.setText(word.getO_name());
        this.t_name.setText(word.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_origName = new javax.swing.JLabel();
        t_name = new javax.swing.JLabel();
        t_usage = new javax.swing.JLabel();
        t_usage_ = new javax.swing.JLabel();
        t_desc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_desc_ = new javax.swing.JTextArea();
        t_lang = new javax.swing.JLabel();

        t_origName.setText("jLabel1");

        t_name.setText("jLabel2");

        t_usage.setText("Usage:");

        t_usage_.setText("jLabel4");

        t_desc.setText("Description:");

        jButton1.setText("Close");

        t_desc_.setColumns(20);
        t_desc_.setRows(5);
        jScrollPane1.setViewportView(t_desc_);

        t_lang.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_name)
                            .addComponent(t_usage)
                            .addComponent(t_usage_)
                            .addComponent(t_desc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_origName)
                                .addGap(18, 18, 18)
                                .addComponent(t_lang)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_origName)
                    .addComponent(t_lang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_name)
                .addGap(18, 18, 18)
                .addComponent(t_usage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_usage_)
                .addGap(18, 18, 18)
                .addComponent(t_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_desc;
    private javax.swing.JTextArea t_desc_;
    private javax.swing.JLabel t_lang;
    private javax.swing.JLabel t_name;
    private javax.swing.JLabel t_origName;
    private javax.swing.JLabel t_usage;
    private javax.swing.JLabel t_usage_;
    // End of variables declaration//GEN-END:variables
}
